ESICFeedback/urls.py
from django.contrib import admin
from django.urls import path,include
import Feedback.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Feedback/',include(Feedback.urls))
]

Feedback/urls.py
from django.urls import path
from django.conf.urls import url

from .import views

urlpatterns = [
    path('',views.homepage,name="homepage"),
    path('Feedbackform/',views.Feedbackform,name="Feedbackform"),
    path('patientfeedback/',views.patientfeedback,name="patientfeedback"),
    path('admindashboard/',views.dashboard,name="dashboard"),
    path('HODSignUp/',views.addHOD,name="addHOD"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout")
]

Feedback/models.py
from django.db import models


class Patient(models.Model):
    patient_ID=models.CharField(max_length=10,primary_key=True,null=False,default=0)
    Rating=models.CharField(max_length=10,null=True,default=None,blank=True)
    department=models.CharField(max_length=50,null=True,default=None,blank=False)
    area_of_issue=models.CharField(max_length=50,null=True,blank=True,default=None)
    explanation=models.CharField(max_length=200,null=True,blank=True,default=None)

    def __str__(self):
        return self.patient_ID

class HOD(models.Model):
    email=models.CharField(max_length=100,primary_key=True,default=None)
    password=models.CharField(max_length=20,default=None,blank=False)

    def __str__(self):
        return self.email

Feedback/forms.py
from django import forms
from .import models


class PatientUpdationForm(forms.Form):
    Rating=forms.CharField()
    department=forms.CharField()
    area_of_issue=forms.CharField()
    explanation=forms.CharField()

class PatientCreationForm(forms.Form):
    patient_ID=forms.CharField()


class HODCreationForm(forms.Form):
    email=forms.CharField()
    password=forms.CharField()

class UserLoginForm(forms.Form):
    email=forms.CharField()
    password=forms.CharField()
    


    

Feedback/views.py
from django.shortcuts import render,redirect
from .forms import PatientCreationForm,PatientUpdationForm,HODCreationForm,UserLoginForm
from . models import Patient,HOD
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
#from django.generic.views import CreateView


def homepage(request):
    return render(request,"Feedback/homepage.html")

def dashboard(request):
    return render(request,'Feedback/dashboard.html')


def addHOD(request):
    if request.method=='POST':
        form=HODCreationForm(request.POST)
        if form.is_valid():
            hod_email=form.cleaned_data['email']
            passwd=form.cleaned_data['password']
            record=HOD(email=hod_email,password=passwd)
            record.save()
            return HttpResponseRedirect(reverse('login'))         
        else:
            field_error="Please Check Your Fields"
            return render(request,'Feedback/HODSignUp.html',{'form':form,'field_error':field_error})
    else:
        form=HODCreationForm()
    return render(request,'Feedback/HODSignUp.html',{'form':form})
    
def login(request):
    if request.method=='POST':
        form=UserLoginForm(request.POST)
        if form.is_valid():
            hod_email=form.cleaned_data['email']
            passwd=form.cleaned_data['password']
            in_HOD=HOD.objects.filter(email=hod_email,password=passwd)
            if in_HOD.exists():
                request.session['admin_ses']=hod_email
                return HttpResponseRedirect(reverse('dashboard'))
            
            else:
                no_account="Your account does not exists"
                return render(request,'Feedback/login.html',{'form':form,'no_account':no_account})         
        else:
            field_error="Invalid Fields"
            return render(request,'Feedback/login.html',{'form':form,'field_error':field_error})

    else:
        form=UserLoginForm()
    return render(request,'Feedback/login.html',{'form':form})




def patientfeedback(request):
    if request.method=='POST':
        form=PatientCreationForm(request.POST)
        if form.is_valid():
            user=form.cleaned_data['patient_ID']
            request.session['user_session']=user
            record=Patient(patient_ID=user,Rating="0",area_of_issue="0",explanation="0")
            record.save()
            return HttpResponseRedirect(reverse('Feedbackform'))         
        else:
            field_error="Please Check Your Fields"
            return render(request,'Feedback/feedbackstart.html',{'form':form,'field_error':field_error})
    else:
        form=PatientCreationForm()
    return render(request,'Feedback/feedbackstart.html',{'form':form})


def Feedbackform(request):
    if request.method=='POST':
        form=PatientUpdationForm(request.POST)
        if form.is_valid():
            rating=form.cleaned_data['Rating']
            Dep=form.cleaned_data['department']
            Area_of_issue=form.cleaned_data['area_of_issue']
            Explanation=form.cleaned_data['explanation']
            currentuser=request.session['user_session']
            record=Patient.objects.filter(patient_ID=currentuser).update(Rating=rating,department=Dep,area_of_issue=Area_of_issue,explanation=Explanation)
            try:
                del request.session['user_session']
            except KeyError:
                pass
            return HttpResponseRedirect(reverse('homepage'))         
        else:
            field_error="Please Check Your Fields"
            return render(request,'Feedback/Feedbackform.html',{'form':form,'field_error':field_error,'currentuser':currentuser})

    else:
        form=PatientUpdationForm()
    
    return render(request,'Feedback/Feedbackform.html',{'form':form})

    


def logout(request):
    try:
        del request.session['admin_ses']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('login'))

Feedback/templates/Feedback/Feedbackform.html
{% extends 'Feedback/base.html' %}
{% block title %}
Feedback
{% endblock %}


{% block body %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class= "d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Please Provide your feedback </h1>
  <!-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
    </div>
    <!-- Content Row -->

    <div class="row">
      <!-- Area Chart -->
      <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Your feedback helps to improve our service</h6>

            <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
          <!-- Card Body -->
          {% load static %}
          <br>
          <div class="card-body">
              <form  method="POST" class="user" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <p style="color: red;">{{ field_error }}</p>
                <p style="color: red;">{{ currentuser }}</p>
                <strong>select Department</strong>
                <select id="id_department" name="department">
                   <option value="General">General</option>
                   <option value="Cardiology">Cardiology</option>
                   <option value="Orthology">Orthology</option>
                   <option value="Neurology">Neurology</option>
                   <option value="Opthomology">Opthomology</option>

                </select>
                <br>
                <br>

                <label><input type="radio" id="id_Rating" name="Rating"  value="excellent" onchange="displaynext(this.value)"/>Excellent</label>
                <br>
                <label><input type="radio" id="id_Rating" name="Rating" value="good" onchange="displaynext(this.value)" />Good</label>
                <br>
                <label><input type="radio" id="id_Rating" name="Rating" value="good" onchange="displaynext(this.value)" />Average</label>
                <br>
                <label><input type="radio" id="id_Rating" name="Rating" value="good" onchange="displaynext(this.value)" />Bad</label>
                <br>
                <label><input type="radio" id="id_Rating" name="Rating" value="good" onchange="displaynext(this.value)" />Worst</label>
                <br>

               

                <div id="goodsomething" style="display:none;">
                  &nbsp;&nbsp;&nbsp;&nbsp;Please Specify the area where you faced the issue
                  <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;<label><input type="radio" id="id_area_of_issue" name="area_of_issue"  value="1" onchange="displayArea(this.value)"/>Hygiene</label>
                  <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;<label><input type="radio" id="id_area_of_issue" name="area_of_issue"  value="2" onchange="displayArea(this.value)"/>Doctor behavior</label>
                  <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;<label><input type="radio"  id="id_area_of_issue" name="area_of_issue"  value="3" onchange="displayArea(this.value)"/>Waiting Time</label>
                  <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;<label><input type="radio"  id="id_area_of_issue" name="area_of_issue"  value="4" onchange="displayArea(this.value)"/>Pharmacy</label>
                  <br>
                   &nbsp;&nbsp;&nbsp;&nbsp;<label><input type="radio" id="id_area_of_issue" name="area_of_issue"  value="5" onchange="displayArea(this.value)"/>Nurse</label>
                  </div>

                   <div id="Input" style="display:none;">
                  &nbsp;&nbsp;&nbsp;&nbsp;Please Explain your issue Briefly
                  <br>
                  <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;<label><input type="text" id="id_explanation" name="explanation" placeholder="Enter Here" /></label>  
                  </div>
                 <br/><br/>
                 <button type="submit" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                  Submit
                </button>
              
              </form>
          </div>
          
      </div>

<script>
   function displaynext(answer)
  {

  document.getElementById(answer + 'something').style.display = "block";
    if (answer == "excellent")
    { 
      document.getElementById('good').style.display = "none";
    }  
  }

  function displayArea(answer) 
  {
    document.getElementById('Input').style.display = "block";
  }
  
</script>      
{% endblock %}

Feedback/templates/Feedback/HODSignUp.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>ESIC - SignUp</title>

  <!-- Custom fonts for this template-->
  {% load static %}
  <link href="{% static 'Feedback/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'Feedback/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-imag">
            <div align="center" style="padding-top:20px;">
            <img src="{% static 'Feedback/img/ESIC.png' style='padding-left:20px;' %}">
          </div>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form action="" class="user" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p style="color:red;">{{ field_errors }}</p>

                <div class="form-group">
                  <input id="id_email" class="form-control form-control-user" type="email"  name="email"  required placeholder="Enter Your Email ID">
                </div>
                <div class="form-group">
                  <input type="password" name="password" class="form-control form-control-user" id="id_password" required placeholder="Enter a password">
                </div>
               
                <button type="submit" class="btn btn-primary btn-user btn-block">
                  Submit
                </button>
                
              </form>
              <hr>
              
              <div class="text-center">
                <a class="small" href="#">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'Feedback/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'Feedback/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'Feedback/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'Feedback/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

Feedback/templates/Feedback/dashboard.html
{% extends 'Feedback/base.html' %}
{% block title %}
Feedback
{% endblock %}


{% block body %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class= "d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Visualization</h1>
  <!-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
    </div>
    <!-- Content Row -->

    <div class="row">
      <!-- Area Chart -->
      <div class="col-xl-6 col-lg-7">
        <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">No of complaints Vs Department</h6>

            <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
          <!-- Card Body -->
          {% load static %}
          <br>
          <div class="card-body">
            <div class="chart-bar">
                <canvas id="myBarChart"></canvas>
              </div>
              <hr>
            </div>
          </div>
          
          </div>


{% endblock %}

Feedback/templates/Feedback/feedbackstart.html
{% extends 'Feedback/base.html' %}
{% block title %}
Feedback
{% endblock %}


{% block body %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class= "d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Please Provide your feedback</h1>
  <!-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
    </div>
    <!-- Content Row -->

    <div class="row">
      <!-- Area Chart -->
      <div class="col-xl-6 col-lg-7">
        <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Your feedback helps to improve our service</h6>

            <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
          <!-- Card Body -->
          {% load static %}
          <br>
          <div class="card-body">
              <form  method="POST" class="user" action="" enctype="multipart/form-data">
                {% csrf_token %}
                 <p style="color: red;">{{ field_error }}</p>
                    
                 <strong >Patient ID</strong>
                 <br>
                 <br>
                 <input type="text" id="id_patient_ID"  name="patient_ID" placeholder="Enter Patient ID">
                 <br>
                 <br>
                 <button type="submit" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                  Continue
                 </button>
              
              </form>
          </div>
          
      </div>


{% endblock %}

Feedback/templates/Feedback/homepage.html
<html>
<head>

</head>
<body>
    <p>hello</p>
</body>


</html>

Feedback/templates/Feedback/login.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>ADMIN - Login</title>

  <!-- Custom fonts for this template-->
  {% load static %}
  <link href="{% static 'Feedback/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'Feedback/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-lgin-image">
                <div align="center" style="padding-top:20px;">
                <img src="{% static 'Feedback/img/ESIC.png' %}">
              </div>
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <p style="color: red;">{{ no_account }}</p>
                    <h1 class="h4 text-gray-900 mb-4">Login to Proceed</h1>
                  </div>
                  <form action="" class="user" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p style="color:red;">{{ field_errors }}</p>
                    <div class="form-group">
                      <input id="id_email" class="form-control form-control-user" type="email"  name="email"  required placeholder="Enter Your Email">
                    </div>
                    <div class="form-group">
                      <input type="password" name="password" class="form-control form-control-user" id="id_password" required placeholder="Enter your Password">
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      Submit
                    </button>
                  
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="#">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="#">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'Feedback/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'Feedback/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'Feedback/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'Feedback/js/sb-admin-2.min.js' %}"></script>

</body>

</html>